# Generated by Django 4.1.1 on 2022-09-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_advertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
